### ISSUE TITLE
use cases contents has funky numbering

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#102]
\1. Evaluate forecasts

\9. Analyze forecasts

\3. Perform forecast evaluation in a standard manner

\6. Administer the framework

**Comment by wholmgren** [comment]
navigation side bar 
<img width="293" alt="Screen Shot 2019-10-24 at 2 46 08 PM" src="https://user-images.githubusercontent.com/4383303/67527951-14a90480-f66d-11e9-8f20-480e07533866.png">

**Comment by wholmgren** [comment]
@lboeman does this make any sense to you? I briefly looked at the html and couldn't figure it out.

**Comment by lboeman** [comment]
Not sure how I didn't notice this, the nesting of list elements is messed up. I'll make a pr to clean it up

**Comment by lboeman** [comment]
Hmm, for some reason this is only rendering that way in firefox.

**Comment by wholmgren** [comment]
Oh, sad. I could have sworn it used to work, so maybe Mozilla introduced a bug at some point. I'm ok letting this sit if it's a firefox only thing.

**Comment by lboeman** [comment]
:+1: Marked wont fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1574398

**Comment by wholmgren** [comment]
😭
