### ISSUE TITLE
Add notes on cost metrics

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/SolarArbiter.github.io#103]
Add content on cost metrics (i.e. the financial costs of mis-forecasting) to the website, based on the document shared by Aidan. Probably add the content to the end of the Metrics page (unless a more obvious place is identified). The content should provide general guidance and mirror the notation used in other parts of the website (e.g. the error metric definitions).

**Comment by wholmgren** [comment]
closed by #110
