### ISSUE TITLE
add user stories or use cases

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#11]

**Comment by wholmgren** [comment]
Converting the google/word doc to markdown would not be too tedious using google docs save as txt and then manually adding ---- ==== and some indentation. I don't know of a better way to do it.

**Comment by lboeman** [comment]
Is the use cases document ready for this? I can take care of it.

**Comment by alorenzo175** [comment]
maybe https://github.com/mangini/gdocs2md

**Comment by cwhanse** [comment]
One more round of edits first, I think
