### ISSUE TITLE
add nmae, nmbe to metrics, clarify normalization

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#141]
Dashboard currently allows for the following report options:

MAPE
NMAE
NMBE
NRMSE

and links to the relevant sections of https://solarforecastarbiter.org/metrics . But the links for NMAE and NMBE are broken since they don't exist on the page.

We should also clarify the normalization rules as discussed in https://github.com/SolarArbiter/solarforecastarbiter-core/issues/269

@dplarson can you take this on?

**Comment by dplarson** [comment]
Sure, I can open a quick PR to address this issue.

**Comment by lboeman** [comment]
closed in #142?

**Comment by dplarson** [comment]
@lboeman yes, this issue should have been closed after #142 was merged.
