### ISSUE TITLE
add links to AMS 2019 slides and poster

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#15]
Maybe put it on the homepage?

https://ams.confex.com/ams/2019Annual/meetingapp.cgi/Paper/354714

**Comment by wholmgren** [comment]
So much for a talk announcement. I'll reuse the issue for the slides and the poster. Perhaps we need a central page for collecting slides, posters, and papers. Maybe also things like the systems layer and data model documentation. @lboeman or anyone else?

**Comment by cwhanse** [comment]
I would add a Publications (or similar heading) link on the main page.  I'd also combine Stakeholder Committee and Contribute somehow, but I don't have a clear idea for a clean combination. Perhaps we ought to have another 'standard' homepage item, About, with Team, Contact, Funding, etc. under this item.

**Comment by cwhanse** [comment]
@lboeman yes, that's the idea - gather up the About items into a drop down menu under About.

**Comment by wholmgren** [comment]
closed by #45
