### ISSUE TITLE
reference data map needs to be checked against the database

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#163]
For example, the reference data map shows a SRML site in Richland but the database does not include it because the data is too old (1996).

Perhaps the thing to do is recreate the google map using a metadata dump from the database. Or perhaps just do https://github.com/SolarArbiter/solarforecastarbiter-dashboard/issues/286

**Comment by wholmgren** [comment]
Map CRN Babbitt Ranches (Meridian Site) appears to be missing in the dashboard.

Map has BLM, Appleton-Whittell Research Ranch. Dashboard has NOAA USCRN Elgin AZ

Dashboard has a site for Williams AZ, but it's not on the map.

The three NM CRN sites all have different names.

Guessing the CRN data has inconsistencies throughout the country.

**Comment by lboeman** [comment]
> Map CRN Babbitt Ranches (Meridian Site) appears to be missing in the dashboard.
> 
> Map has BLM, Appleton-Whittell Research Ranch. Dashboard has NOAA USCRN Elgin AZ
> 
> Dashboard has a site for Williams AZ, but it's not on the map.
> 
> The three NM CRN sites all have different names.
> 
> Guessing the CRN data has inconsistencies throughout the country.
I removed the SRML sites that no longer exist in the database.

Looks like on the reference data map, the USCRN data has a "Name" field. In `sfa_reference_sites.csv` the names for these sites was built from the "Location" and "State" field.  For instance, the Williams AZ site is Babbitt Ranches (Meridian Site). Maybe this was to avoid going over the name length limit?

**Comment by lboeman** [comment]
Should I update all the USCRN sites on the map with the dashboard names?

**Comment by wholmgren** [comment]
Yes any reason not to?

**Comment by lboeman** [comment]
This should be up to date with the database now.
- All USCRN sites renamed to the database names. 
- Removed Oak Right SOLRAD site that does not exist in the db.
- Removed PVDAQ CIS 1 site that does not exist in the db.

**Comment by wholmgren** [comment]
looks good, thanks!
