### ISSUE TITLE
allow users to sign up for a mailing list

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#18]
Implementation depends on what kind of system we use for a mailing list. Might only need a link to another page. That's a separate discussion.

And no signup feature unless they can also unsubscribe.

**Comment by lboeman** [comment]
This has been implemented in #20 . However, the sign up form is on the front page and will probably get moved around so this issue should stay open until we're happy with it.

**Comment by wholmgren** [comment]
@lboeman can you add a list checkbox for "Solar Forecasting 2 team members"?

**Comment by lboeman** [comment]
Added!

**Comment by wholmgren** [comment]
long gone
