### ISSUE TITLE
add reference data map

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#29]
We should add a link or even embed the @lboeman's nice reference data map. It's not clear to me where it should go. We might need a new Reference Data section. Thoughts?

**Comment by lboeman** [comment]
I think the navigation is getting cramped, perhaps the metrics, data policies, benchmark forecasts and reference data section could go in a "Project Details" tab?
I've made the map public as well as opened a pull request, #30 , to make placement more straightforward. It should also make addressing concerns about the mailchimp form placement simpler.
I verified that using a static embedded google map is free.

**Comment by wholmgren** [comment]
You are right about a lot on the header. And we're going to add Use Cases too. But there is still room on my screen! I think we should just put it in the header because I don't want to think too hard about redesign at this point.
