### ISSUE TITLE
adjust data model for regular observations

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/SolarArbiter.github.io#59]
and allow missing values. Also add recommendations for resampling

**Comment by wholmgren** [comment]
Not sure I follow... Is this still an issue?

**Comment by alorenzo175** [comment]
I'm not quite sure either. I think this is saying that we should say on the data model page that observations must conform to the interval length when they are uploaded. This might require resampling of the data and missing values as placeholders when there is no data in the series.
