### ISSUE TITLE
Replace metrics document with HTML

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/SolarArbiter.github.io#71]
Currently, the metrics page links to a document that summarizes the metrics. Instead, it would be better to list out the metrics on the metrics page itself (e.g. as a bullet point list).

The main question with this approach is how to represent mathematical symbols (e.g. the square root in the RMSE definition). There are libraries for rendering LaTeX in an HTML page (e.g. MathJax), which may be better than trying to use an ASCII-representation (e.g. `RMSE = sqrt( 1/n * sum( (F_i - O_i)^2 ) )`).

**Comment by dplarson** [comment]
Just realized the website already includes MathJax. So I'll move ahead with revising the metrics page to render LaTeX equations using MathJax.

**Comment by dplarson** [comment]
Before I go too far with this, how does something like this look to everyone? @cwhanse @alorenzo175 @lboeman

![Screen Shot 2019-06-13 at 2 36 19 PM](https://user-images.githubusercontent.com/1169109/59469099-baf41c00-8de8-11e9-9eb9-0d9e25570003.png)

Notes:
- The equations are written using LaTeX, which is then rendered using MathJax.
- Since we're using LaTeX, we could use the notation of `y` as the true value and `\hat{y}` as the predicted value. Or we can stick with the current `F` is the forecast and `O` is the observation.

**Comment by alorenzo175** [comment]
I think it would be easier to read if the equations were centered on a line below the name/description. This might require putting HTML in the markdown document. I don't have any preference on O/F vs ``y`` ``\hat{y}`` as long as a sentence at the top describes the notation.

**Comment by dplarson** [comment]
That turns out to be easy in MathJax/Markdown:

![Screen Shot 2019-06-13 at 2 52 40 PM](https://user-images.githubusercontent.com/1169109/59469911-fb549980-8dea-11e9-9b10-f9e9f6ed3844.png)

**Comment by dplarson** [comment]
Related: should we include just the definitions of each metric or also include the descriptions of each metric (from the metrics proposal document)?

For quick reference, here's the description for MAE and RMSE form the proposal document:

![Screen Shot 2019-06-13 at 3 05 02 PM](https://user-images.githubusercontent.com/1169109/59470489-b2054980-8dec-11e9-9308-0f003389ae52.png)

**Comment by cwhanse** [comment]
I'd include the verbal descriptions.  Some of the editorial statements could be omitted, e.g., "One shortcoming...."  Keep the descriptions and usage instructions, e.g., "The normalizing factor must have the same units...."  In case of "It is common to use AC capacity as the normalizing factor.." we should state what the Arbiter does.

How do we efficiently define the terms, e.g.,  `F` and `O` need to be defined.  Maybe a table of common symbols at the top of the page, and specific terms defined with the metrics.

**Comment by dplarson** [comment]
With #74 now merged, this issue can be closed.
