### ISSUE TITLE
Update climate zone map

### ISSUE THREAD

**Issue by dplarson** [SolarArbiter/SolarArbiter.github.io#79]
Update the climate zone map with more refined outlines of the climate zones, preferably in the form of a GIS-type file (e.g. a shapefile) that can be re-used in the future.

- [x] refine the climate zones
   - [x] save in a re-usable GIS-type format (e.g. a shapefile)
- [x] update the climate zone plot
   - [x] replace the current figure file with the revised one (PNG or JPG format)

**Comment by dplarson** [comment]
For easy reference, here's the current climate zones map from the Solar Arbiter website:

![climatezones](https://user-images.githubusercontent.com/1169109/63976216-b0e7ce00-ca65-11e9-8a8f-e59d25970e6c.png)

**Comment by alorenzo175** [comment]
@dplarson were you planning on taking this on? If not, I will.

**Comment by dplarson** [comment]
@alorenzo175 If you've got time now, feel free to take this on. (I probably won't get to this until next week.)

**Comment by alorenzo175** [comment]
Here's my attempt at hopefully following Justin's intent with the zones. Did I get it mostly right @MrWindAndSolar?

I think it would be nice as a Bokeh plot vs a png. @wholmgren ?
[
![map](https://user-images.githubusercontent.com/4625457/63986468-e5b94c80-ca88-11e9-88a9-e4dafd1009cc.png)
](url)

**Comment by MrWindAndSolar** [comment]
Tony this is pretty darn close.  The one thing I'd like to do is look at the coast regions more closely as the transitions typically occur on terrain and are very rapid so placement is important (and my original isn't great either :-).  Do you have a kml I could load into Google Earth.

**Comment by alorenzo175** [comment]
Yup, KML files are on the team drive here https://drive.google.com/drive/folders/1pMs0CYrEVEpYVCcUvjFuWSmjVxUu7l9C 

I think the SF bay area can definitely use some adjustment.

**Comment by wholmgren** [comment]
Agree that it would be nice to serve a dynamic plot (from static html?) if it's not too much work. Definitely want to link to kml or other formats from the same page.

**Comment by MrWindAndSolar** [comment]
I'll start the discussion tomorrow using the great map in issue #80, and then drop to GE to discuss in more geographic detail if appropriate.  Having a quality terrain map will be very helpful for the discussion.  Thanks to all involved.

**Comment by alorenzo175** [comment]
I've updated the KML files to match those shown on the website and added a KMZ files with colors to the drive as ClimateZones (1).kmz. Maybe better to use this new file for consistency, unless there were other modifications.

**Comment by dplarson** [comment]
@alorenzo175 The revised maps and files are looking good. There are a few minor revisions I want to suggest (e.g. tighten the Southern California zone 1 to the coastline, thereby removing the ocean overlap), but I think those can be covered by separate follow-up issues.

If no one has a complaint, I think I'll go ahead and close this issue as being completed.

**Comment by MrWindAndSolar** [comment]
I've made my final updates and also updated the documentation (pull request submitted as I don't have access to the main branch).  Tony is going to finalize the details of region overlaps and then I think we can stick a fork in this one.

**Comment by MrWindAndSolar** [comment]
Incorporated Will's comments and requests.  Ready to merge.

**Comment by alorenzo175** [comment]
@dplarson The KML etc files are up on the site now with the updated zones
