### ISSUE TITLE
update dashboard documentation for real users

### ISSUE THREAD

**Issue by wholmgren** [SolarArbiter/SolarArbiter.github.io#90]
The [getting started](https://solarforecastarbiter.org/documentation/dashboard/#getting-started) section describes how to use test log in information. Not sure if we want to keep the test info, but we definitely need to say how to use real log in. 

Perhaps also move the data access control help page's [account creation](https://solarforecastarbiter.org/data-access-workflow/#account-creation) and [establishing or joining an organization](https://solarforecastarbiter.org/data-access-workflow/#establishing-or-joining-an-organization) sections into the primary dashboard help page.

**Comment by lboeman** [comment]
closed in #100 
With an updated getting started page. https://solarforecastarbiter.org/documentation/dashboard/getting-started/
