### ISSUE TITLE
Document exatly what each permission does

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/SolarArbiter.github.io#98]
Not sure if this belongs here, but we should document what permissions allow. For example, having the write_values permission allows one to write values to specified id but also allows one to read the interval_length of the parent object and to get the last value uploaded before a certain time.

**Comment by wholmgren** [comment]
At this point, `dataaccessworkflow.md` is the best fit.

**Comment by lboeman** [comment]
In thinking about the dashboard issues, I created a spreadsheet of the effects of each permission action on the content types.
https://docs.google.com/spreadsheets/d/1CwR9glFoWMhvbauPAK-FgMp8j6jKTEDFEjYLa2mICgo/edit
This reflects the permissions from an end user perspective so I haven't included that write_values allows reading interval_length in the SQL. 

Would adding a more verbose version of this table be useful in the documentation?

**Comment by alorenzo175** [comment]
I think it would be

**Comment by wholmgren** [comment]
Cool. That helps.
